# This file was generated by GoReleaser. DO NOT EDIT.
cask "pr-manager" do
  version "0.1.16"

  on_macos do
    on_arm do
      sha256 "3f5f487f982435e47550054d92885501e0837ba31d3a297de0c06fafaaee5c78"
      url "https://github.com/amitbet/pr-manager/releases/download/v#{version}/pr-manager_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "dd7336fa09ed348db99489be9711030eec472fe5cacbb6b09b935e9a51c5b7c1"
      url "https://github.com/amitbet/pr-manager/releases/download/v#{version}/pr-manager_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b4bf2ee50177c8c89e10b02c05421dc494407219ab405a8213729da656ba0d02"
      url "https://github.com/amitbet/pr-manager/releases/download/v#{version}/pr-manager_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "708c7ca45aeb6ef3b36f523141ebdce5243be17eae01cc3366160ada1644fee2"
      url "https://github.com/amitbet/pr-manager/releases/download/v#{version}/pr-manager_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pr-manager"
  desc "Sort pull request changes by the human review they need"
  homepage "https://github.com/amitbet/pr-manager"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
      "git",
    ]

  binary "pr-manager"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pr-manager"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `gh auth login`, then `pr-manager serve`.
    Install Go for full Go call graphs; otherwise indexing uses declarations only.
  EOS
end
