# This file is generated by scripts/desktop-cask.sh on release. DO NOT EDIT.
cask "pr-manager-desktop" do
  version "0.1.59"
  sha256 "20fb630e4f768d7d36b7ed730fd1c71cc3493f37e06b4ec3f6bd677b722ee834"

  url "https://github.com/amitbet/pr-manager/releases/download/v#{version}/PR-Manager-macos-arm64.zip"
  name "PR Manager"
  desc "Desktop app that sorts pull request changes by the human review they need"
  homepage "https://github.com/amitbet/pr-manager"

  livecheck do
    skip "Auto-generated on release."
  end

  depends_on arch: :arm64
  depends_on formula: [
    "gh",
    "git",
  ]

  # The app's executable is also the pr-manager command line, so the
  # separate pr-manager cask is not needed next to it.
  conflicts_with cask: "amitbet/pr-manager/pr-manager"

  app "PR Manager.app"
  binary "#{appdir}/PR Manager.app/Contents/MacOS/pr-manager"

  # The app is ad-hoc signed but not notarized.
  postflight_steps do
    run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{appdir}}/PR Manager.app"]
  end

  caveats <<~EOS
    Run `gh auth login` before opening PR Manager.
    The `pr-manager` command comes with the app, e.g. `pr-manager fix` in a checkout.
  EOS
end
