# This file was generated by GoReleaser. DO NOT EDIT.
cask "pr-manager" do
  version "0.1.10"

  on_macos do
    on_arm do
      sha256 "f8926c0cfeca50faf8c992c25abd71225b7d6b466d0fc89892889e9271cad9e0"
      url "https://github.com/amitbet/pr-manager/releases/download/v#{version}/pr-manager_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "cbdd304433434746a425ba0d9e086df902ab4e5784c53f8bda36bd65595237ab"
      url "https://github.com/amitbet/pr-manager/releases/download/v#{version}/pr-manager_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "f36f3af760cda7ed5b0f52a54712c5234909bb60033877fbff8dfdb184dfb898"
      url "https://github.com/amitbet/pr-manager/releases/download/v#{version}/pr-manager_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e42a973072cc633fe417bfc85f9b5b04f4859c287c734aca9e31cf5957944887"
      url "https://github.com/amitbet/pr-manager/releases/download/v#{version}/pr-manager_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pr-manager"
  desc "Sort pull request changes by the human review they need"
  homepage "https://github.com/amitbet/pr-manager"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
      "git",
    ]

  binary "pr-manager"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pr-manager"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `gh auth login`, then `pr-manager serve`.
    Install Go for full Go call graphs; otherwise indexing uses declarations only.
  EOS
end
