# This file was generated by GoReleaser. DO NOT EDIT.
cask "pr-manager" do
  version "0.1.18"

  on_macos do
    on_arm do
      sha256 "77ecd165f882c991a19a0bc8ec0bdf9a4ff290c74faa35e709edffa715c59445"
      url "https://github.com/amitbet/pr-manager/releases/download/v#{version}/pr-manager_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "0d394ba0750cb98ae2f653a69218ae77eac316e97ac42ada5fbf1cd5b7bcb568"
      url "https://github.com/amitbet/pr-manager/releases/download/v#{version}/pr-manager_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "577a116aca50df90f61f9e6cd687faa9c0804c6dff1219e066a17e06ae527757"
      url "https://github.com/amitbet/pr-manager/releases/download/v#{version}/pr-manager_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "821ec3637d921ab2d8393902e714ce2793d9f98e5adf6ec319afbdafd42e05f6"
      url "https://github.com/amitbet/pr-manager/releases/download/v#{version}/pr-manager_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pr-manager"
  desc "Sort pull request changes by the human review they need"
  homepage "https://github.com/amitbet/pr-manager"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
      "git",
    ]

  binary "pr-manager"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pr-manager"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `gh auth login`, then `pr-manager serve`.
    Install Go for full Go call graphs; otherwise indexing uses declarations only.
  EOS
end
