package triage

import (
	"os"
	"regexp"
	"strings"
	"testing"
)

func TestParsePRPolicyIgnoresHeadLoosening(t *testing.T) {
	head := []byte("generated: [\"*.go\"]\nforce_human: [\"secrets/\"]\nthresholds:\n  none: 0.1\n  skim: 0.1\nmax_unit_chars: 999999\ntiers:\n  review_budget: light\nlint:\n  enabled: false\n")
	p, err := ParsePRPolicy(nil, head)
	if err != nil {
		t.Fatal(err)
	}
	def := DefaultPolicy()
	if _, ok := MatchAny(p.Generated, "svc/retry.go"); ok {
		t.Error("the head's generated patterns must not apply")
	}
	if p.Thresholds != def.Thresholds || p.MaxUnitChars != def.MaxUnitChars || p.Tiers.ReviewBudget != def.Tiers.ReviewBudget || !p.Lint.Enabled {
		t.Errorf("the head loosened the policy: %+v", p)
	}
	if _, ok := MatchAny(p.ForceHuman, "secrets/key.txt"); !ok {
		t.Error("the head's force_human patterns should still apply")
	}

	// The base's file is trusted whole; the head only adds force_human.
	base := []byte("generated: [\"*.gen.ts\"]\nthresholds:\n  none: 0.95\n")
	p, err = ParsePRPolicy(base, head)
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := MatchAny(p.Generated, "api/client.gen.ts"); !ok || p.Thresholds.None != 0.95 {
		t.Errorf("base policy not applied: %+v", p)
	}
	if _, ok := MatchAny(p.Generated, "svc/retry.go"); ok {
		t.Error("the head's generated patterns must not apply over a base file")
	}
	if _, err := ParsePRPolicy(base, []byte("{not yaml")); err != nil {
		t.Errorf("a broken head file should add nothing, not fail: %v", err)
	}
}

func wsUnit(file string, lines ...string) *Unit {
	return &Unit{File: file, Status: StatusModified, Hunks: []Hunk{{Header: "@@ -1,2 +1,2 @@", Lines: lines}}}
}

func TestPresortWhitespace(t *testing.T) {
	cases := []struct {
		name   string
		u      *Unit
		format bool
	}{
		{"trailing space", wsUnit("svc/a.go", " func f() {", "-\tx := 1  ", "+\tx := 1", " }"), true},
		{"blank lines", wsUnit("svc/a.go", " func f() {", "+", "+\t", "-\tx := 1 ", "+\tx := 1", " }"), true},
		// The diff scanner drops a trailing CR, so a CRLF -> LF line reads the same.
		{"line ending", wsUnit("svc/a.go", "-\tx := 1", "+\tx := 1"), false},
		{"space after backslash", wsUnit("build/run.sh", "-go build \\ ", "+go build \\", " ./..."), false},
		{"blank line after continuation", wsUnit("build/run.sh", " go build \\", "+", " ./..."), false},
		{"python docstring file", wsUnit("app/main.py", " def f():", `+    """doc`, "-    x ", "+    x", `     """`), false},
		{"js template literal", wsUnit("web/a.js", " const s = `", "-  a ", "+  a", " `"), false},
		{"go raw string, no content", wsUnit("svc/a.go", " var s = `", "-  a ", "+  a", " `"), false},
		{"space in a string", wsUnit("svc/a.go", `-	s := "a b"`, `+	s := "a  b"`), false},
		{"indentation", wsUnit("svc/a.go", "-\tx := 1", "+\t\tx := 1"), false},
		{"python indentation", wsUnit("app/main.py", "-        return x", "+    return x"), false},
		{"python trailing space", wsUnit("app/main.py", "-    return x ", "+    return x"), true},
		{"markdown trailing space", wsUnit("docs/a.md", "-hard break  ", "+hard break"), true},
		{"yaml", wsUnit("deploy/app.yml", "-  key: v", "+    key: v"), false},
		{"makefile", wsUnit("build/Makefile", "-\tgo build", "+    go build"), false},
	}
	for _, c := range cases {
		// RealChanges is empty: every file looks unchanged under git diff -w.
		src := &Source{Files: []FileDiff{{Path: c.u.File}}, RealChanges: map[string]bool{}}
		(&Presorter{Policy: DefaultPolicy()}).Presort([]*Unit{c.u}, src)
		if got := c.u.Decision.ChangeKind == "format"; got != c.format {
			t.Errorf("%s: format=%v want %v (%+v)", c.name, got, c.format, c.u.Decision)
		}
	}
}

func TestMentionsMatchesWordBoundaryRegexp(t *testing.T) {
	texts := []string{"", "Foo", "Foo()", "xFoo Foo", "Foox", "_Foo", "a.Foo.b", "FooFoo Foo", "é Foo", "Foo\n", "FoFoo", "9Foo", "Foo9 Foo_"}
	for _, name := range []string{"Foo", "Fo", "a.b", "Foo_"} {
		for _, text := range texts {
			want := len(name) >= 3 && identRe.MatchString(name) && regexp.MustCompile(`\b`+name+`\b`).MatchString(text)
			if got := mentions(text, name); got != want {
				t.Errorf("mentions(%q, %q) = %v, want %v", text, name, got, want)
			}
		}
	}
}

func TestHasGeneratedHeader(t *testing.T) {
	cases := []struct {
		name, file, src string
		want            bool
	}{
		{"go", "api/x.pb.go", "// Code generated by protoc-gen-go. DO NOT EDIT.\n\npackage api\n", true},
		{"go after build tag", "api/x.go", "//go:build linux\n\n// Code generated by stringer; DO NOT EDIT.\n\npackage api\n", true},
		{"go after license", "api/x.go", "/*\n Copyright 2024\n*/\n\n// Code generated by mockgen. DO NOT EDIT.\npackage api\n", true},
		{"go no final period", "api/x.go", "// Code generated by x. DO NOT EDIT\npackage api\n", false},
		{"go const string", "gen/main.go", "package main\n\nconst header = \"// Code generated by gen. DO NOT EDIT.\"\n", false},
		{"go raw string template", "gen/tmpl.go", "package gen\n\nvar tmpl = `\n// Code generated by gen. DO NOT EDIT.\n`\n", false},
		{"go comment after package", "gen/main.go", "package main\n\n// Code generated by gen. DO NOT EDIT.\n", false},
		{"ts", "web/api.ts", "/* eslint-disable */\n// Code generated by openapi. DO NOT EDIT.\nexport const x = 1\n", true},
		{"ts block", "web/api.ts", "/**\n * Code generated by openapi-generator. DO NOT EDIT.\n */\nexport const x = 1\n", true},
		{"ts const string", "tools/gen.ts", "const header = '// Code generated by gen. DO NOT EDIT.'\n", false},
		{"python", "app/x_pb2.py", "#!/usr/bin/env python\n# Code generated by protoc. DO NOT EDIT.\nimport x\n", true},
		{"python after code", "app/gen.py", "import os\n# Code generated by gen. DO NOT EDIT.\n", false},
		{"python string", "app/gen.py", "HEADER = \"# Code generated by gen. DO NOT EDIT.\"\n", false},
		{"sql", "db/q.sql", "-- Code generated by sqlc. DO NOT EDIT.\nSELECT 1;\n", true},
		{"xml", "res/a.xml", "<?xml version=\"1.0\"?>\n<!-- Code generated by x. DO NOT EDIT. -->\n<a/>\n", true},
		{"protoc python", "app/x_pb2.py", "# -*- coding: utf-8 -*-\n# Generated by the protocol buffer compiler.  DO NOT EDIT!\n# source: x.proto\nimport x\n", true},
		{"dotnet", "App/Form1.Designer.cs", "//------------------------------------------------------------------------------\n// <auto-generated>\n//     This code was generated by a tool.\n// </auto-generated>\n//------------------------------------------------------------------------------\nnamespace App {}\n", true},
		{"mid-line", "web/a.ts", "// see: Code generated ... DO NOT EDIT headers\nexport const x = 1\n", false},
	}
	for _, c := range cases {
		got := hasGeneratedHeader(func(string) ([]byte, error) { return []byte(c.src), nil }, c.file)
		if got != c.want {
			t.Errorf("%s: got %v want %v", c.name, got, c.want)
		}
	}
}

func TestDefaultGeneratedPatterns(t *testing.T) {
	gen := DefaultPolicy().Generated
	for file, want := range map[string]bool{
		"vendor/github.com/x/y/a.go":         true,
		"web/node_modules/react/index.js":    true,
		"src/features/vendor/VendorForm.tsx": false,
		"app/models/vendor/payout.rb":        false,
		"pkg/id/uuid_gen.go":                 false,
		"internal/store/mocks/store.go":      false,
		// Generated source goes by its header, not its name.
		"internal/store/store_mock.go":         false,
		"pkg/payments/mock_client.go":          false,
		"api/v1/types.pb.go":                   false,
		"pkg/apis/v1/zz_generated.deepcopy.go": false,
		"go.sum":                               true,
		"web/package-lock.json":                true,
	} {
		if _, got := MatchAny(gen, file); got != want {
			t.Errorf("%s: generated=%v want %v", file, got, want)
		}
	}
	// A repo can still opt in.
	p, err := ParsePolicy([]byte("generated: [\"mocks/\", \"*_gen.go\"]\n"))
	if err != nil {
		t.Fatal(err)
	}
	for _, f := range []string{"internal/store/mocks/store.go", "pkg/id/uuid_gen.go"} {
		if _, ok := MatchAny(p.Generated, f); !ok {
			t.Errorf("%s: user pattern not applied", f)
		}
	}
}

// A mock under mocks/ is generated only when its header says so.
func TestPresortMocksNeedHeader(t *testing.T) {
	files := map[string]string{
		"internal/store/mocks/store.go": "// Code generated by MockGen. DO NOT EDIT.\npackage mocks\n",
		"internal/store/mocks/fake.go":  "package mocks\n\ntype Fake struct{}\n",
	}
	src := &Source{Content: func(f string) ([]byte, error) { return []byte(files[f]), nil }}
	for f := range files {
		src.Files = append(src.Files, FileDiff{Path: f})
	}
	for f, want := range map[string]bool{"internal/store/mocks/store.go": true, "internal/store/mocks/fake.go": false} {
		u := wsUnit(f, "-\tx := 1", "+\tx := 2")
		(&Presorter{Policy: DefaultPolicy()}).Presort([]*Unit{u}, src)
		if got := u.Decision.ChangeKind == "generated"; got != want {
			t.Errorf("%s: generated=%v want %v (%+v)", f, got, want, u.Decision)
		}
	}
}

// A generated header only skips review when the merge base had it too: a
// PR can write the header, or pick a generated-looking name, for code that
// ships.
func TestPresortGeneratedHeaderNeedsBase(t *testing.T) {
	const header = "// Code generated by MockGen. DO NOT EDIT.\npackage payments\n"
	const plain = "package payments\n\nfunc Charge() {}\n"
	cases := []struct {
		name, file string
		status     FileStatus
		head, base string
		old        string
		bucket     Bucket // "" : no rule decides it
	}{
		{"modified, header at base", "pkg/payments/mock_client.go", StatusModified, header, header, "", BucketNone},
		{"modified, header added by the PR", "pkg/payments/client.go", StatusModified, header, plain, "", BucketSkim},
		{"added with header", "pkg/payments/mock_client.go", StatusAdded, header, "", "", BucketSkim},
		{"added generated name, no header", "pkg/payments/mock_client.go", StatusAdded, plain, "", "", ""},
		{"modified generated name, no header", "api/v1/types.pb.go", StatusModified, plain, plain, "", ""},
		{"renamed, header at the old path", "pkg/payments/mock_new.go", StatusRenamed, header, header, "pkg/payments/mock_old.go", BucketNone},
	}
	for _, c := range cases {
		head := map[string]string{c.file: c.head}
		base := map[string]string{}
		if c.status != StatusAdded {
			old := c.old
			if old == "" {
				old = c.file
			}
			base[old] = c.base
		}
		read := func(m map[string]string) ContentFunc {
			return func(f string) ([]byte, error) {
				s, ok := m[f]
				if !ok {
					return nil, os.ErrNotExist
				}
				return []byte(s), nil
			}
		}
		src := &Source{Files: []FileDiff{{Path: c.file, OldPath: c.old, Status: c.status}}, Content: read(head), BaseContent: read(base)}
		u := wsUnit(c.file, "-\tx := 1", "+\tx := 2")
		u.Status = c.status
		(&Presorter{Policy: DefaultPolicy()}).Presort([]*Unit{u}, src)
		if u.Decision.Bucket != c.bucket {
			t.Errorf("%s: %+v, want bucket %q", c.name, u.Decision, c.bucket)
		}
	}
	// Without the base content the header can't be checked, so it is reviewed.
	src := &Source{Files: []FileDiff{{Path: "a/x.go"}}, Content: func(string) ([]byte, error) { return []byte(header), nil }}
	u := wsUnit("a/x.go", "-\tx := 1", "+\tx := 2")
	(&Presorter{Policy: DefaultPolicy()}).Presort([]*Unit{u}, src)
	if u.Decision.Bucket != BucketSkim {
		t.Errorf("no base: %+v", u.Decision)
	}
}

func TestDocsAndManifests(t *testing.T) {
	for file, docs := range map[string]bool{
		"README.md":                true,
		"docs/guide.rst":           true,
		"LICENSE.txt":              true,
		"notes/todo.txt":           true,
		"requirements.txt":         false,
		"svc/requirements-dev.txt": false,
		"dev-requirements.txt":     false,
		"requirements/prod.txt":    false,
		"constraints.txt":          false,
		"native/CMakeLists.txt":    false,
		"web/public/robots.txt":    false,
		"runtime.txt":              false,
	} {
		if got := isDocs(file); got != docs {
			t.Errorf("isDocs(%q) = %v, want %v", file, got, docs)
		}
	}
	fh := DefaultPolicy().ForceHuman
	for _, f := range []string{"go.mod", "web/package.json", "requirements.txt", "svc/requirements-dev.txt", "requirements/prod.txt", "pyproject.toml", "Gemfile", "Cargo.toml", "pom.xml", "app/build.gradle.kts", "src/App/App.csproj", "native/CMakeLists.txt"} {
		if _, ok := MatchAny(fh, f); !ok {
			t.Errorf("%s: not force_human", f)
		}
	}
	for _, f := range []string{"go.sum", "web/package-lock.json", "Cargo.lock", "poetry.lock", "Gemfile.lock"} {
		if _, ok := MatchAny(fh, f); ok {
			t.Errorf("%s: a lockfile should not be force_human", f)
		}
	}
}

func TestPresortForceHumanOldPath(t *testing.T) {
	u := &Unit{File: "build/go.mod.bak", Status: StatusRenamed}
	src := &Source{Files: []FileDiff{{Path: u.File, OldPath: "go.mod", Status: StatusRenamed}}}
	(&Presorter{Policy: DefaultPolicy()}).Presort([]*Unit{u}, src)
	if u.Decision.Bucket != BucketHuman {
		t.Errorf("rename away from go.mod: %+v", u.Decision)
	}
}

func TestInertRename(t *testing.T) {
	cases := []struct {
		old, new string
		want     bool
	}{
		{"svc/retry.go", "svc/backoff.go", true},
		{"svc/retry.go", "pkg/retry.go", false},
		{"svc/retry.go", "svc/retry_test.go", false},
		{"svc/retry_linux.go", "svc/retry_unix.go", false},
		{"svc/retry_linux_amd64.go", "svc/retry_linux_arm64.go", false},
		{"svc/retry_linux.go", "svc/backoff_linux.go", true},
		{"svc/retry.go", "svc/retry.txt", false},
		{"web/util.ts", "web/lib/util.ts", true},
		{"web/util.ts", "web/index.ts", false},
		{"app/conf.py", "app/conftest.py", false},
		{"app/x.py", "app/__init__.py", false},
		{"Dockerfile", "Dockerfile.old", false},
		{"cmd/app.go", "cmd/main.go", false},
		{"", "a.go", false},
	}
	for _, c := range cases {
		if got := inertRename(c.old, c.new); got != c.want {
			t.Errorf("%s -> %s: got %v want %v", c.old, c.new, got, c.want)
		}
	}
	u := &Unit{File: "pkg/retry.go", Status: StatusRenamed}
	src := &Source{Files: []FileDiff{{Path: u.File, OldPath: "svc/retry.go", Status: StatusRenamed}}}
	if rest := (&Presorter{Policy: DefaultPolicy()}).Presort([]*Unit{u}, src); len(rest) != 1 {
		t.Errorf("a Go file moved to another package should reach the classifier: %+v", u.Decision)
	}
}

func TestPresortWhitespaceContent(t *testing.T) {
	const goFile = "package a\n\nvar s = `\n  a  \n`\n\nfunc f() {\n\tx := 1\n}\n"
	const goNew = "package a\n\nvar s = `\n  a\n`\n\nfunc f() {\n\tx := 1\n}\n"
	read := func(s string) ContentFunc { return func(string) ([]byte, error) { return []byte(s), nil } }
	hunk := func(start int, lines ...string) *Unit {
		return &Unit{File: "svc/a.go", Status: StatusModified, Hunks: []Hunk{{OldStart: start, NewStart: start, Lines: lines}}}
	}
	cases := []struct {
		name       string
		u          *Unit
		base, head string
		format     bool
	}{
		// Line 4 is inside the raw string; line 8 is code, with the string elsewhere.
		{"in raw string", hunk(4, "-  a  ", "+  a"), goFile, goNew, false},
		{"outside raw string", hunk(8, "-\tx := 1 ", "+\tx := 1"), strings.Replace(goFile, "x := 1", "x := 1 ", 1), goFile, true},
		{"crlf", hunk(8, "-\tx := 1 ", "+\tx := 1"), strings.ReplaceAll(strings.Replace(goFile, "x := 1", "x := 1 ", 1), "\n", "\r\n"), goFile, false},
	}
	for _, c := range cases {
		src := &Source{Files: []FileDiff{{Path: c.u.File}}, RealChanges: map[string]bool{}, Content: read(c.head), BaseContent: read(c.base)}
		(&Presorter{Policy: DefaultPolicy()}).Presort([]*Unit{c.u}, src)
		if got := c.u.Decision.ChangeKind == "format"; got != c.format {
			t.Errorf("%s: format=%v want %v (%+v)", c.name, got, c.format, c.u.Decision)
		}
	}
}

func TestIsFixture(t *testing.T) {
	cases := map[string]bool{
		"testdata/jvm/jdk17.txt":              true,
		"containers/testdata/cases.go":        true, // Go never builds testdata
		"src/test/resources/logback-test.xml": true,
		"svc/src/test/resources/Sample.java":  true,
		"fixtures/users.json":                 true,
		"web/__fixtures__/page.html":          true,
		"test/data/input.csv":                 true,
		"tests/expected.txt":                  true,
		"pkg/__tests__/payload.yaml":          true,
		"spec/fixtures/response.json":         true,
		"fixtures/factory.js":                 false, // helper code keeps its review
		"tests/test_api.py":                   false,
		"test/README.md":                      false, // docs, not data
		"tests/tsconfig.json":                 false, // changes how tests build
		"tests/jest.config.json":              false,
		"tests/.eslintrc.json":                false,
		"tests/requirements.txt":              false,
		"test/pytest.ini":                     false,
		"config/app.yaml":                     false,
		"latest/notes.txt":                    false, // a segment, not a substring
		"contest/data.json":                   false,
	}
	for f, want := range cases {
		if got := isFixture(f); got != want {
			t.Errorf("isFixture(%q) = %v, want %v", f, got, want)
		}
	}
}
