package triage

import (
	"bytes"
	"regexp"
	"slices"
	"strings"
)

// Presorter applies deterministic rules. Units it decides never reach an LLM.
type Presorter struct {
	Policy Policy
	// GitattributesGenerated are linguist-generated patterns.
	GitattributesGenerated []string
}

// Presort sets Decision on units a rule can decide and returns the rest.
func (p *Presorter) Presort(units []*Unit, src *Source) (rest []*Unit) {
	files := map[string]FileDiff{}
	for _, f := range src.Files {
		files[f.Path] = f
	}
	for _, u := range units {
		if d, ok := p.rule(u, files[u.File], src); ok {
			d.Source = "rule"
			u.Decision = d
			continue
		}
		rest = append(rest, u)
	}
	return rest
}

func (p *Presorter) rule(u *Unit, f FileDiff, src *Source) (Decision, bool) {
	// Forced-human wins over everything, including "generated".
	if pat, ok := MatchAny(p.Policy.ForceHuman, u.File); ok {
		return Decision{Bucket: BucketHuman, ChangeKind: "config", Reason: "path matches force_human policy " + pat}, true
	}
	if f.Binary {
		return Decision{Bucket: BucketHuman, ChangeKind: "binary", Reason: "binary file"}, true
	}
	if pat, ok := MatchAny(p.Policy.Generated, u.File); ok {
		return Decision{Bucket: BucketNone, ChangeKind: "generated", Reason: "generated file (" + pat + ")"}, true
	}
	if pat, ok := MatchAny(p.GitattributesGenerated, u.File); ok {
		return Decision{Bucket: BucketNone, ChangeKind: "generated", Reason: "linguist-generated in .gitattributes (" + pat + ")"}, true
	}
	// The head's header is the PR's own claim: a PR could put it on a
	// hand-written file to keep it from review. It skips review only when
	// the file already carried it at the merge base; a new file, or a
	// header this PR added, is still reviewed.
	if u.Status != StatusDeleted && src.Content != nil && hasGeneratedHeader(src.Content, u.File) {
		if baseGenerated(u, f, src) {
			return Decision{Bucket: BucketNone, ChangeKind: "generated", Reason: "file has a Code generated ... DO NOT EDIT header, as it did at the merge base"}, true
		}
		return Decision{Bucket: BucketSkim, ChangeKind: "generated", Reason: "generated header the merge base did not have (new file or new header), so it is still reviewed", Confidence: 1}, true
	}
	if u.Status == StatusRenamed && len(u.Hunks) == 0 {
		return Decision{Bucket: BucketNone, ChangeKind: "rename", Reason: "pure rename, content identical"}, true
	}
	if src.RealChanges != nil && len(u.Hunks) > 0 && !src.RealChanges[u.File] && trailingSpaceOnly(u) {
		return Decision{Bucket: BucketNone, ChangeKind: "format", Reason: "trailing whitespace / blank lines only"}, true
	}
	if strings.HasSuffix(u.File, ".go") {
		if d, ok := goBoilerplate(u); ok {
			return d, true
		}
	}
	if isDocs(u.File) {
		return Decision{Bucket: BucketSkim, ChangeKind: "docs", Reason: "documentation file", Confidence: 1}, true
	}
	return Decision{}, false
}

// trailingSpaceOnly reports whether the unit's removed and added lines are
// the same once trailing whitespace and blank lines are dropped. git diff -w
// also ignores indentation and spaces inside a line, which can change a
// string literal or, in some languages, the program.
func trailingSpaceOnly(u *Unit) bool {
	var removed, added []string
	for _, h := range u.Hunks {
		for _, l := range h.Lines {
			if l == "" || (l[0] != '+' && l[0] != '-') {
				continue
			}
			t := strings.TrimRight(l[1:], " \t\r\f\v")
			if t == "" {
				continue
			}
			if l[0] == '+' {
				added = append(added, t)
			} else {
				removed = append(removed, t)
			}
		}
	}
	return slices.Equal(removed, added)
}

// baseGenerated reports whether the file had a generated header at the
// merge base too, under its old name if the PR renamed it.
func baseGenerated(u *Unit, f FileDiff, src *Source) bool {
	if u.Status == StatusAdded || src.BaseContent == nil {
		return false
	}
	old := f.OldPath
	if old == "" {
		old = u.File
	}
	return hasGeneratedHeader(src.BaseContent, old)
}

// goGenerated is the Go convention (go help generate); the line must come
// before the package clause.
var goGenerated = regexp.MustCompile(`^// Code generated .* DO NOT EDIT\.$`)

// commentOpeners start a comment line in the languages generators write.
var commentOpeners = []string{"<!--", "/*", "//", "--", "#", ";", "*"}

// hasGeneratedHeader reports whether the file starts with a "Code generated
// ... DO NOT EDIT" comment, or outside Go the markers protoc and .NET
// write ("Generated by the protocol buffer compiler.  DO NOT EDIT!",
// "<auto-generated>"). Only the header counts: the comments before the
// first line of code. A generator's own source holds the phrase in a
// string, which is not a comment, and hand-written code comes before it.
func hasGeneratedHeader(content ContentFunc, file string) bool {
	src, err := content(file)
	if err != nil {
		return false
	}
	head := src
	if len(head) > 2048 {
		head = head[:2048]
	}
	isGo := strings.HasSuffix(file, ".go")
	inBlock := false // inside a /* or <!-- comment opened on an earlier line
	for _, line := range bytes.Split(head, []byte("\n")) {
		raw := strings.TrimRight(string(line), " \t\r")
		s := strings.TrimSpace(raw)
		if s == "" {
			continue
		}
		if isGo {
			if goGenerated.MatchString(raw) {
				return true
			}
			switch {
			case inBlock:
				inBlock = !strings.Contains(s, "*/")
			case strings.HasPrefix(s, "//"):
			case strings.HasPrefix(s, "/*"):
				inBlock = !strings.Contains(s[2:], "*/")
			default:
				return false // the package clause or code: past the header
			}
			continue
		}
		text, ok := "", false
		if inBlock {
			text, ok = s, true
			if strings.HasPrefix(text, "*") && !strings.HasPrefix(text, "*/") {
				text = text[1:]
			}
		} else if strings.HasPrefix(s, "#!") || strings.HasPrefix(s, "<?") {
			continue // a shebang, or an XML declaration or PHP open tag
		} else {
			for _, o := range commentOpeners {
				if strings.HasPrefix(s, o) {
					text, ok = strings.TrimLeft(s[len(o):], "/#;-*!"), true
					inBlock = (o == "/*" && !strings.Contains(s[2:], "*/")) || (o == "<!--" && !strings.Contains(s[4:], "-->"))
					break
				}
			}
		}
		if !ok {
			return false
		}
		if inBlock && (strings.Contains(s, "*/") || strings.Contains(s, "-->")) {
			inBlock = false
		}
		text = strings.TrimSpace(strings.TrimSuffix(strings.TrimSuffix(strings.TrimSpace(text), "*/"), "-->"))
		if (strings.HasPrefix(text, "Code generated") || strings.HasPrefix(text, "Generated by the protocol buffer compiler")) && strings.Contains(text, "DO NOT EDIT") {
			return true
		}
		if strings.HasPrefix(text, "<auto-generated") {
			return true
		}
	}
	return false
}

// notDocs are .txt files that a tool reads: dependency lists, build files
// and web server config. They change what gets installed, built or served.
var notDocs = []string{
	"*requirements*.txt", "requirements/", "constraints*.txt", "cmakelists.txt",
	"robots.txt", "runtime.txt",
}

func isDocs(file string) bool {
	lower := strings.ToLower(file)
	if strings.HasSuffix(lower, ".txt") {
		_, manifest := MatchAny(notDocs, lower)
		return !manifest
	}
	return strings.HasSuffix(lower, ".md") || strings.HasSuffix(lower, ".rst")
}

var (
	blankOrDotImport = regexp.MustCompile(`^[+-]\s*(import\s+)?[_.]\s+"`)
	importLine       = regexp.MustCompile(`^[+-]\s*(import\s*\(?|\)|(\w+\s+)?"[^"]*"|import\s+(\w+\s+)?"[^"]*")?\s*(//.*)?$`)
	packageLine      = regexp.MustCompile(`^[+-]\s*(package\s+\w+)?\s*(//.*)?$`)
)

var (
	importSpec  = regexp.MustCompile(`^[+-]\s*(?:import\s*\(?\s*)?(?:(\w+)\s+)?"([^"]*)"`)
	majorSuffix = regexp.MustCompile(`^v[0-9]+$`)
)

type goImport struct{ alias, path string }

// importSwap reports whether the changed import lines rebind a name to
// another package: a spec removed and one added under the same name, like
// "crypto/rand" -> rand "math/rand" or foo "x/v1" -> foo "x/v2". The code
// using the name still compiles, so the compiler proves nothing. Specs
// removed and re-added unchanged (reordering, regrouping) cancel out.
func importSwap(changed []string) bool {
	var removed, added []goImport
	for _, l := range changed {
		m := importSpec.FindStringSubmatch(l)
		if m == nil {
			continue
		}
		if l[0] == '-' {
			removed = append(removed, goImport{m[1], m[2]})
		} else {
			added = append(added, goImport{m[1], m[2]})
		}
	}
	for i := 0; i < len(removed); i++ {
		if j := slices.Index(added, removed[i]); j >= 0 {
			added = slices.Delete(added, j, j+1)
			removed = slices.Delete(removed, i, i+1)
			i--
		}
	}
	for _, r := range removed {
		for _, a := range added {
			if r.path != a.path && sharesName(importNames(r), importNames(a)) {
				return true
			}
		}
	}
	return false
}

// importNames is the name an import binds: its alias, or else the package
// name, which only the package clause gives for sure. The guesses cover
// the usual ways it differs from the last path element: a /vN major
// version suffix, gopkg.in's .vN, and go-/-go around the name. A wrong
// guess only costs a classifier call.
func importNames(im goImport) []string {
	if im.alias != "" {
		return []string{im.alias}
	}
	elems := strings.Split(im.path, "/")
	last := elems[len(elems)-1]
	if majorSuffix.MatchString(last) && len(elems) > 1 {
		last = elems[len(elems)-2]
	}
	names := []string{last}
	for _, part := range strings.FieldsFunc(last, func(r rune) bool { return r == '-' || r == '.' }) {
		if part != "go" && !majorSuffix.MatchString(part) {
			names = append(names, part)
		}
	}
	return names
}

func sharesName(a, b []string) bool {
	for _, n := range a {
		if slices.Contains(b, n) {
			return true
		}
	}
	return false
}

// goBoilerplate decides units whose changed lines are only import specs or
// the package clause. Blank and dot imports run init code, and a name
// moved to another package changes what its uses call, so those go to the
// classifier.
func goBoilerplate(u *Unit) (Decision, bool) {
	var changed []string
	for _, h := range u.Hunks {
		for _, l := range h.Lines {
			if strings.HasPrefix(l, "+") || strings.HasPrefix(l, "-") {
				changed = append(changed, l)
			}
		}
	}
	if len(changed) == 0 {
		return Decision{}, false
	}
	all := func(re *regexp.Regexp) bool {
		for _, l := range changed {
			if !re.MatchString(l) {
				return false
			}
		}
		return true
	}
	switch {
	case u.Symbol == "imports" && all(importLine):
		for _, l := range changed {
			if blankOrDotImport.MatchString(l) {
				return Decision{}, false
			}
		}
		if importSwap(changed) {
			return Decision{}, false
		}
		return Decision{Bucket: BucketNone, ChangeKind: "format", Reason: "import list only (the compiler rejects unused imports; uses are in other units)"}, true
	case u.Symbol == "" && all(packageLine):
		return Decision{Bucket: BucketNone, ChangeKind: "format", Reason: "package clause / blank lines only"}, true
	}
	return Decision{}, false
}
